# Generated by Django 3.1.5 on 2021-04-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0002_auto_20210430_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
