# Generated by Django 3.1.5 on 2021-04-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0003_attendance_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='latitide',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
