# Generated by Django 3.1.5 on 2021-04-30 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0004_auto_20210501_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='latitide',
            new_name='latitude',
        ),
    ]
